package co.edu.uniquindio.compiladores.lexico

enum class Categoria {
    ENTERO, DECIMAL, IDENTIFICADORV, OPERADOR_ARITMETICO, OPERADOR_LOGICO, PARENTESIS_IZQ, PARENTESIS_DER, PUNTO, COMA,
    OPERADOR_RELACIONAL, INCREMENTO, DECREMENTO, DESCONOCIDO, PALABRA_RESERVADA_ENTERO, PALABRA_RESERVADA_CADENA_CARACTERES,
    PALABRA_RESERVADA_CARACTERES, PALABRA_RESERVADA_FLOAT, PALABRA_RESERVADA_DOUBLE , OPERADOR_TERMINAL , LLAVE_IZQ ,
    LLAVE_DER, PALABRA_RESERVADA_METODO_PRINCIPAL , CADENA_CARACTERES, COMENTARIO, OPERADOR_ASIGNACION , BUCLE ,
    DESICION , IDENTIFICADORM
}